# The URL the site will be built for
base_url = "https://www.bitranchlabs.com/"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
minify_html = true
smart_punctuation = true
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", feed = true},
]

[markdown]
highlight_code = true

[extra]
